/*
 * SPDX-FileCopyrightText: 2022-2025 Espressif Systems (Shanghai) CO LTD
 *
 * SPDX-License-Identifier: Apache-2.0
 */

/**
 * @file
 * @brief This file was generated by esp_mmap_assets, don't modify it
 */

#pragma once

#include "esp_mmap_assets.h"

#define MMAP_FONTS_FILES           1
#define MMAP_FONTS_CHECKSUM        0x01B6

enum MMAP_FONTS_LISTS {
    MMAP_FONTS_LV_FONT_DISHES_BIN = 0,        /*!< lv_font_dishes.bin */
};
